server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: user_service_user
    password: user_service_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tcc

management:
  endpoints:
    web:
      exposure:
        include: health,info

tcc:
  security:
    enabled: true
    opa:
      enabled: true
      url: http://localhost:8181/v1/data/user/authz/decision
      timeout: 2s
    headers:
      purpose: X-Purpose
      data-subject-id: X-Data-Subject-Id
      correlation-id: X-Correlation-Id