server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/user_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/tcc}

management:
  endpoints:
    web:
      exposure:
        include: health,info

tcc:
  security:
    enabled: true
    opa:
      enabled: true
      url: ${OPA_URL:http://localhost:8181/v1/data/user/authz/decision}
      timeout: 2s
    headers:
      purpose: X-Purpose
      data-subject-id: X-Data-Subject-Id
      correlation-id: X-Correlation-Id
